### ISSUE TITLE
Bubble Vision is unwishable

### ISSUE THREAD

**Issue by KennyMan666** [Ezandora/Genie#4]
Currently, the 100% Item buff button starts out as Frosty if you have no +100% item buffs, becomes One Very Clear Eye if you have Frosty, and Bubble Vision if you have both Frosty and One Very Clear Eye. The Genie can however not actually grant Bubble Vision, so the third choice for +100% items should probably be Certainty or something.

**Comment by Ezandora** [comment]
Fixed in some version.
