### ISSUE TITLE
Some monsters no longer available, one effect no longer available

### ISSUE THREAD

**Issue by GustavBertram** [Ezandora/Genie#6]
Got errors until I removed the relevant code from choice.1267.ash:

> Using data override: relay/choice.1267.ash
> Bad monster value: "mouthless murmur" (choice.1267.ash, line 4371)
> Bad monster value: "The Silent Nightmare" (choice.1267.ash, line 4371)
> Bad effect value: "I'll Have the Soup" (choice.1267.ash, line 4373)

**Comment by Ezandora** [comment]
This is due to running an older copy of Mafia; the [latest build](https://ci.kolmafia.us/job/Kolmafia/lastSuccessfulBuild/) supports it.
